title: jaqbiak
email: jaqbiak88@gmail.com
description: >-
  jaqbiak's personal page
baseurl: ""
url: "https://jaqbiak.space"
github_username:  jaqbiak

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - "_assets"
